spring:
  application:
    name: aws-utils
  rabbitmq:
    username: ${RABBIT_USER}
    password: ${RABBIT_PASSWORD}
    addresses: ${RABBIT_URI}
logging:
  level:
    root: info
server:
  port: 0
aws:
  access: ${AWS_ACCESS}
  secret: ${AWS_SECRET}
  content:
    bucket:
      name: ${AWS_CONTENT_BUCKET}
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI}
management:
  zipkin:
    tracing:
      endpoint: ${ZIPKIN_URI}/api/v2/spans
  tracing:
      sampling:
        probability: 1.0